server:
  port: 8888

spring:
  application:
    name: Gateway
  cloud:
    consul:
      host: localhost
      port: 8500
    discovery:
      enabled: true
management:
  endpoints:
    web:
      exposure:
        include: health
  endpoint:
    health:
      show-details: always